language: c
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
env:
  - EXTRA=libpcsclite-dev
script:
  - ./build-and-test.sh
matrix:
  include:
    - compiler: gcc
      os: linux
      env: EXTRA="wine mingw-w64 mingw-w64-i686-dev" REMOVE=mingw32 ARCH=32
    - compiler: gcc
      os: linux
      env: EXTRA="wine mingw-w64 mingw-w64-x86-64-dev" REMOVE=mingw32 ARCH=64
    - compiler: gcc
      os: linux
      env: COVERAGE="--enable-coverage" EXTRA="libpcsclite-dev lcov"
    - compiler: gcc
      os: linux
      env: BUILD_OPENSSL_VERSION="1.1" EXTRA="libpcsclite-dev"
